### PR TITLE
Added command for opening Twitter

### PR DESCRIPTION
**Pull request by chiragbhansali**
### Requirements

* Filling out the template is required. Any pull request that does not include enough information to be reviewed in a timely manner may be closed at the maintainers' discretion.
* All new code requires tests to ensure against regressions

### Description of the Change

This pull request adds a command to open Twitter from Cato

### Alternate Designs

None

### Why Should This Be In Core?

Creates a shortcut for Twitter

### Benefits

Makes accessing Twitter easy

### Possible Drawbacks

Might contribute to command bloat

### CODE REVIEW

**Comment by Olian04** [comment]
@chiragbhansali cato is a general purpose command pallet, and IMO commands that open social media pages isn't something that cato would benefit from.

**Comment by chiragbhansali** [comment]
@Olian04: For that matter, even having a command to open Amazon isn't beneficial. Nevertheless, a feature to make shortcuts for websites will be helpful. Thanks

**Comment by cliffordfajardo** [comment]
@chiragbhansali @Olian04 - I need to configure Cato to allow users to create their own simple commands, like adding websites. 

I'm planning a refactor of the app soon & you'll be to create your own simple commands like this one.

**Comment by cliffordfajardo** [comment]
Please refer to [this issue comment ](https://github.com/cliffordfajardo/cato/pull/18#issuecomment-353506690)

**Pull request closed without merging**
